select connection_in_midle_of_filter_up_and_sushi.sushi_id, connection_in_midle_of_filter_up_and_sushi.filter_up_id, connection_in_midle_of_filter_ingredients_and_sushi.ingredient_id from connection_in_midle_of_filter_ingredients_and_sushi
join connection_in_midle_of_filter_up_and_sushi on connection_in_midle_of_filter_ingredients_and_sushi.sushi_id = connection_in_midle_of_filter_up_and_sushi.sushi_id
where connection_in_midle_of_filter_up_and_sushi.filter_up_id = 1 or connection_in_midle_of_filter_up_and_sushi.filter_up_id = 2 and connection_in_midle_of_filter_ingredients_and_sushi.ingredient_id = 1;

на строке where фильтрация верхней части фильтера от фильтрации нижней части фильтера отделяется словом and